cc_library(
    name = "renderControl_dec",
    srcs = [
        "renderControl_dec.cpp",
        "renderControl_server_context.cpp",
    ] + glob(["*.h"]),
    hdrs = [],
    visibility = ["//visibility:public"],
    deps = [
        "@gfxstream//common/opengl:gfxstream_opengl_headers",
        "@gfxstream//host/apigen-codec-common",
    ],
)
