module(name = "gfxstream")

bazel_dep(name = "bazel_skylib", version = "1.7.1", dev_dependency = True)

bazel_dep(name = "googletest", version = "1.15.2", repo_name = "com_google_googletest")
bazel_dep(name = "platforms", version = "0.0.11")
bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "rules_license", version = "1.0.0")
bazel_dep(name = "toolchains_llvm", version = "1.2.0")

# Configure and register the toolchain.
llvm = use_extension("@toolchains_llvm//toolchain/extensions:llvm.bzl", "llvm")
llvm.toolchain(
    llvm_version = "18.1.8",
)
use_repo(llvm, "llvm_toolchain")

register_toolchains("@llvm_toolchain//:all")

bazel_dep(name = "aemu", version = "1")

git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "angle",
    commit = "5c2789e0f185a3c7fff624907423a5054376b282",
    remote = "https://chromium.googlesource.com/angle/angle",
)

#git_repository = use_repo_rule("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
#git_repository(
#    name = "aemu",
#    commit = "01e8060ea3c0437ea167d0e744d6aaf7c7173f54",
#    remote = "https://android.googlesource.com/platform/hardware/google/aemu",
#)

local_path_override(
    module_name = "aemu",
    path = "../aemu",
)

local_path_override(
    module_name = "googletest",
    path = "../../../external/googletest",
)
