// Copyright (C) 2024 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package gfxstream.host.snapshot;

message VirtioGpuResourceCreateArgs {
    uint32 id = 1;
    uint32 target = 2;
    uint32 format = 3;
    uint32 bind = 4;
    uint32 width = 5;
    uint32 height = 6;
    uint32 depth = 7;
    uint32 array_size = 8;
    uint32 last_level = 9;
    uint32 nr_samples = 10;
    uint32 flags = 11;
}

message VirtioGpuIovec {
    uint64 addr = 1;
    uint64 size = 2;
}

// LINT.IfChange(virtio_gpu_resource)
message VirtioGpuResourceSnapshot {
    uint32 id = 1;
    VirtioGpuResourceCreateArgs create_args = 2;
    repeated VirtioGpuIovec iovs = 4;
}
// LINT.ThenChange(VirtioGpuResource.h:virtio_gpu_resource)
