# Copyright 2024 Android Open Source Project
# SPDX-License-Identifier: MIT

inc_common_fdstream = include_directories('include')

files_lib_common_fdstream = files(
  'Strings.cpp',
)

lib_common_fdstream = static_library(
  'common_fdstream',
  files_lib_common_fdstream,
  include_directories: [inc_common_fdstream],
)