package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "gfxstream-gl-server",
    srcs = [
        "BufferGl.cpp",
        "ColorBufferGl.cpp",
        "CompositorGl.cpp",
        "DebugGl.cpp",
        "DisplayGl.cpp",
        "DisplaySurfaceGl.cpp",
        "EmulatedEglConfig.cpp",
        "EmulatedEglContext.cpp",
        "EmulatedEglFenceSync.cpp",
        "EmulatedEglImage.cpp",
        "EmulatedEglWindowSurface.cpp",
        "EmulationGl.cpp",
        "GLESVersionDetector.cpp",
        "ReadbackWorkerGl.cpp",
        "TextureDraw.cpp",
        "TextureResize.cpp",
        "YUVConverter.cpp",
    ],
    hdrs = glob([
        "*.h",
    ]),
    includes = ["."],
    copts = [
        "-fno-exceptions",
        "-Wno-extern-c-compat",
    ],
    defines = [
        "GFXSTREAM_ENABLE_HOST_GLES=1",
        "EMUGL_BUILD",
    ],
    deps = [
        "//host/gl/OpenGLESDispatch:gfxstream_opengles_dispatch",
        "//host/gl/gl-host-common:gfxstream_gl_host_common",
        "//host/gl/gles1_dec:gfxstream_gles1_decoder",
        "//host/gl/gles2_dec:gfxstream_gles2_decoder",
        "@aemu//base:aemu-base-headers",
        "@aemu//host-common:aemu-host-common-headers",
        "//host:gfxstream_host_headers",
        "//host/apigen-codec-common",
        "//host/gl/glsnapshot:gfxstream_glsnapshot",
        "//include:gfxstream_openglesdispatch_headers",
    ],
)
