package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "gfxstream_gles2_decoder",
    srcs = [
        "GLESv2Decoder.cpp",
        "gles2_dec.cpp",
        "gles2_server_context.cpp",
    ] + glob(["*.h"]),
    copts = ["-fno-exceptions"],
    defines = ["EMUGL_BUILD"],
    deps = [
        "//host/gl/glsnapshot:gfxstream_glsnapshot",
        "@aemu//base:aemu-base-headers",
        "@aemu//host-common:aemu-host-common-headers",
        "//common/opengl:gfxstream_opengl_headers",
        "//include:gfxstream_renderutils",
        "//host/apigen-codec-common",
    ],
)
