package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "gfxstream_gles1_decoder",
    srcs = [
        "GLESv1Decoder.cpp",
        "gles1_dec.cpp",
        "gles1_server_context.cpp",
    ] + glob(["*.h"]),
    copts = ["-fno-exceptions"],
    defines = ["EMUGL_BUILD"],
    deps = [
        "//common/opengl:gfxstream_opengl_headers",
        "//host/apigen-codec-common",
        "//host/gl/glsnapshot:gfxstream_glsnapshot",
        "//include:gfxstream_renderutils",
    ],
)
