# Copyright 2025 Android Open Source Project
# SPDX-License-Identifier: Apache-2.0 or MIT

files_lib_gfxstream_logging = files(
  'logging.cpp',
)

lib_gfxstream_logging = static_library(
  'lib_gfxstream_logging',
  files_lib_gfxstream_logging,
  include_directories: [inc_stream_servers,
                        inc_host_include],
)
