package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "gfxstream_utils",
    srcs = ["GfxApiLogger.cpp"],
    hdrs = glob(["include/**/*.h"]),
    copts = ["-fno-exceptions"],
    includes = ["include"],
    deps = [
        "//common/vulkan:gfxstream_vulkan_headers",
        "//third-party/renderdoc",
        "@aemu//base:aemu-base-headers",
        "@aemu//host-common:aemu-host-common-headers",
    ],
)

cc_test(
    name = "gfxstream_utils_unittests",
    srcs = [
        "GfxApiLogger_unittest.cpp",
        "RenderDoc_unittest.cpp",
    ],
    deps = [
        ":gfxstream_utils",
        "@com_google_googletest//:gtest_main",
    ],
)
