cc_library(
    name = "GLES_CM_translator_static",
    srcs = [
        "CoreProfileEngine.cpp",
        "GLEScmContext.cpp",
        "GLEScmImp.cpp",
        "GLEScmUtils.cpp",
        "GLEScmValidate.cpp",
    ] + glob(["*.h"]),
    copts = [
        "-Wno-extern-c-compat",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@aemu//snapshot:aemu-snapshot",
        "@gfxstream//:gfxstream-gl-host-common-headers",
        "@gfxstream//host/apigen-codec-common",
        "@gfxstream//host/gl:gl_common",
        "@gfxstream//third-party/glm",
    ],
)
