package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "GLES_CM_translator_static",
    srcs = [
        "CoreProfileEngine.cpp",
        "GLEScmContext.cpp",
        "GLEScmImp.cpp",
        "GLEScmUtils.cpp",
        "GLEScmValidate.cpp",
    ] + glob(["*.h"]),
    copts = [
        "-Wno-extern-c-compat",
    ],
    deps = [
        "@aemu//base:aemu-base-headers",
        "@aemu//host-common:aemu-host-common-headers",
        "//host/apigen-codec-common",
        "//host/gl/glestranslator/GLcommon:gfxstream_glestranslator_glcommon",
        "//third-party/glm",
        "@aemu//snapshot:aemu-snapshot",
    ],
)
