package(
    default_visibility = ["//:gfxstream_packages"],
)

cc_library(
    name = "gfxstream_opengles_dispatch",
    srcs = [
        "EGLDispatch.cpp",
        "GLESv1Dispatch.cpp",
        "GLESv2Dispatch.cpp",
        "OpenGLDispatchLoader.cpp",
        "StaticDispatch.cpp",
        "gles1_stubbed_in_translator_namespace.cpp",
        "gles2_stubbed_in_translator_namespace.cpp",
    ],
    copts = [
        "-fno-exceptions",
        "-Wno-extern-c-compat",
    ],
    defines = ["EMUGL_BUILD"],
    deps = [
        "//host/gl/glestranslator/EGL:gfxstream_egl_translator",
        "//host/gl/gles1_dec:gfxstream_gles1_decoder",
        "//host/gl/gles2_dec:gfxstream_gles2_decoder",
        "@aemu//base:aemu-base-headers",
        "@aemu//host-common:aemu-host-common-headers",
        "//include:gfxstream_openglesdispatch_headers",
        "//common/opengl:gfxstream_opengl_headers",
        "//host/apigen-codec-common",
    ],
)
